### ISSUE TITLE
Operand like == != >= <=

### ISSUE THREAD

**Issue by IPE-Pierre** [mormat/php-formula-interpreter#16]
all in title :)

would be nice to have it working

(a=1) returns true
(a=1)*150 triggers an error

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the OperationCommand class to ensure that the equal operator returns the result of the comparison instead of a boolean value. This allows expressions like (a=1)*150 to work correctly.

You can review changes in this commit: https://github.com/mnmnk43434/mormat-php-formula-interpreter-16/commit/2f0633008986dc2356884d76884ce27e2b78a362.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by IPE-Pierre** [comment]
Hello I thing the function implementation got it worked see https://github.com/mormat/php-formula-interpreter/issues/17

simply implement the function equal and reference 

although there is an error I don't get :
`150+100*greater(m+n,5)+(equal(b,1)*150+equal(c,1)*150+equal(d,1)*150+equal(f,1)*150+equal(g,1)*100+equal(h,1)*50+equal(i,1)*50+equal(j,1)*150+equal(k,1)*50+equal(l,1)*50)`

It's going through

now that I put someting like :
`150+100*greater(m+n,5)+(equal(b,1)*150+equal(c,1)*150+equal(d,1)*150+equal(f,1)*150+equal(g,1)*100+equal(h,1)*50+equal(i,1)*50+equal(j,1)*150+equal(k,1)*50+equal(l,1)*50) * ( 1-0.05)`

I have an error Failed to parse expression ( 1

**Comment by IPE-Pierre** [comment]
THe logic I want to implement is by adding this `*(1-0.05*equal(b+c+d+f+g+h+i+j+k+l,2)-0.1*equal(b+c+d+f+g+h+i+j+k+l,3)-0.15*equal(b+c+d+f+g+h+i+j+k+l,4)-0.2*equal(b+c+d+f+g+h+i+j+k+l,5)-0.25*((b+c+d+f+g+h+i+j+k+l)>5)`

**Comment by IPE-Pierre** [comment]
equation like this :
`150+(equal(b,1)*150+equal(c,1)*150+equal(d,1)*150+equal(f,1)*150+equal(g,1)*100+equal(h,1)*50+equal(i,1)*50+equal(j,1)*150+equal(k,1)*50+equal(l,1)*50)*(1+0.05)`

wouldn't work too though :
`(equal(b,1)*150+equal(c,1)*150+equal(d,1)*150+equal(f,1)*150+equal(g,1)*100+equal(h,1)*50+equal(i,1)*50+equal(j,1)*150+equal(k,1)*50+equal(l,1)*50)*(1+0.05)`

works

**Comment by IPE-Pierre** [comment]
you can simplify the problem to 
`'150+(b*150)*(1+0.05)'`

though 150+((b*150)*(1+0.05)) works

there is some missing order group missing

**Comment by mormat** [comment]
In the commit 9710ab86f1be2a8a31542e9cabc8f251022d0d7b, the expressions below can now be compiled : 
- `150+(b*150)*(1+0.05)`
- `(equal(b,1)*150+equal(c,1)) * ( 1-0.05)`

**Comment by IPE-Pierre** [comment]
ho you are quick !
