### ISSUE TITLE
Dealing with multiple bracketed expressions

### ISSUE THREAD

**Issue by Toyinster** [mormat/php-formula-interpreter#4]
I am getting ParserException: Failed to parse expression '1.5)/(1' when parsing the following formula:

> '(((100 * 0.43075) * 1.1 * 1.5) / (1-0.425)) * 1.105'

Is there anyway this could be fixed by perhaps evaluating sub-expression first?

**Comment by adre81** [comment]
Also 1+(1+1)

**Comment by mormat** [comment]
Thank you for your feedback.

I have fixed the issue.
